Added test for -n|--dry-run and implemented it.
Now the -n or --dry-run option will output a 'theoretical' renaming of
files, but will not make any changes to the filesystem. This is useful
when, for example, one is checking if the files are acceptable by the
script.

Added output to signify the dry run. Also refactored test to clean up
after itself, and refactored non-DRY test.

diff --git a/date-dedash b/date-dedash
--- a/date-dedash
+++ b/date-dedash
@@ -54,7 +54,7 @@ do
     ret=1
     continue
   fi
-  echo "Processing $f ..."
+  [ -n "$DRY_RUN" ] && echo -e "This is a \033[33mDRY RUN\033[0m. No changes will be made." || echo "Processing $f ..."
   if [[ ( $f =~ ^([0-9]{4})-?([0-9]{2})-?([0-9]{2})\ *(-\ *)?(.*)$ ) ]] # Has an 8 digit number, maybe date, at front
   then # echo "Congrats: File $f passes 8-digit number test."
     year=${BASH_REMATCH[1]}
@@ -71,9 +71,13 @@ do
       # echo "Proceeding to adjust creation/modification date."
       # echo "BASH_REMATCH: ${BASH_REMATCH}; full_date: $full_date"
       # echo "desc: $desc"
-      if `mv $f "$full_date $desc"`
-      then : # echo "   Success! $f was de-dashed."
-      else { ERRCODE=$?; echo "Error code $ERRCODE. Exiting."; exit $ERRCODE; }
+      if [ -n "$DRY_RUN" ]; then
+        echo "$f  ->  $full_date $desc"
+      else
+        if `mv $f "$full_date $desc"`
+        then : # echo "   Success! $f was de-dashed."
+        else { ERRCODE=$?; echo "Error code $ERRCODE. Exiting."; exit $ERRCODE; }
+        fi
       fi
     else echo "Error: $f has an invalid date in filename."
     fi
