Added BATS bash testing framework. Corrected typos.
Updated formatting, spacing, etc. Added test for invalid filename, and implemented it. Added overall return
value that returns if any of the files were invalid.

diff --git a/date-dedash b/date-dedash
--- a/date-dedash
+++ b/date-dedash
@@ -2,11 +2,17 @@
 
 SAVEIFS=$IFS
 IFS=$(echo -en "\n\b")
+ret=0
 for f in $*
 do
+  if [ ! -f "$f" ]; then
+    echo "date-dedash: no such file '$f'"
+    ret=1
+    continue
+  fi
   echo "Processing $f file..."
   if [[ ( $f =~ ^([0-9]{4})-?([0-9]{2})-?([0-9]{2})\ *(-\ *)?(.*)$ ) ]] # Has an 8 digit number, maybe date, at front
-  then # echo "Congrats: File $f passes 8-digit number test." 
+  then # echo "Congrats: File $f passes 8-digit number test."
     year=${BASH_REMATCH[1]}
     month=${BASH_REMATCH[2]}
     day=${BASH_REMATCH[3]}
@@ -25,10 +31,11 @@ do
       then : # echo "   Success! $f was de-dashed."
       else { ERRCODE=$?; echo "Error code $ERRCODE. Exiting."; exit $ERRCODE; }
       fi
-    else echo "Error: $f has invalidate date in filename."
+    else echo "Error: $f has an invalid date in filename."
     fi
   else echo "Error: $f needs date with format YYYYMMDD at beginning of filename with trailing space."
   fi
-
+  
 done
 IFS=$SAVEIFS
+exit $ret
